#vGenerates scrambled vs z correlation plots directly from generated Master Tables
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as PathEffects
from scipy.stats import spearmanr
import os

# ==========================================
# 1. FILE PATHS & SETUP
# ==========================================
base_dir = r"..\data\\" 
ccf_csv = os.path.join(base_dir, "CCFv3-2020_info_oliver_voxel_info.csv")

# Input files generated by the previous scripts
ai34_z_file = os.path.join(base_dir, "Ai34_Master_Tables_Formatted.xlsx")
ai34_scram_file = os.path.join(base_dir, "Ai34_Scram_Master_Tables_TwoWay.xlsx")

ai14_z_file = os.path.join(base_dir, "Ai14_Master_Tables_Formatted.xlsx")
ai14_scram_file = os.path.join(base_dir, "Ai14_Scram_Master_Tables_TwoWay.xlsx")

output_dir = r"..\output\\" 

# ==========================================
# 2. ALLEN ATLAS MAPPING LOGIC 
# ==========================================
ccf_df = pd.read_csv(ccf_csv)
abbrev_to_parent = dict(zip(ccf_df['abbreviation'], ccf_df['region']))
abbrev_to_parent['PTLp'] = 'PTLp'

allen_colors = {
    'Isocortex': '#66C2A5', 
    'HPF': '#7ED04B', 
    'CTXsp': '#8DD3D7', 
    'CNU': '#98D6F9', 
    'IB': '#FF7080', 
    'MB': '#FF64FF', 
    'VS': '#B39DDB'         
}

def get_base_group(region_parent):
    if region_parent in ['PL', 'ILA', 'AI', 'PERI', 'ECT', 'ORB', 'VISC', 'VIS', 'TEa', 'MO', 'SS', 'ACA', 'RSP', 'AUD', 'PTLp', 'PTL', 'FRP', 'GU', 'ISO']: return 'Isocortex'
    if region_parent in ['ENT', 'PAR', 'HATA', 'SUB', 'ProS', 'PRE', 'POST', 'DG', 'CA3', 'CA2', 'CA1', 'IG', 'HPF', 'RHP', 'HIP', 'FC']: return 'HPF'
    if region_parent in ['EP', 'PA', 'CLA', 'BMA', 'BLA', 'LA', 'CTXsp']: return 'CTXsp'
    if region_parent in ['SI', 'MS', 'TRS', 'GP', 'BST', 'PAL', 'FS', 'OT', 'ACB', 'CP', 'MEA', 'AAA', 'IA', 'SH', 'SF', 'LS', 'STR']: return 'CNU'
    if region_parent in ['VPM', 'VPL', 'VM', 'VAL', 'SPA', 'SPF', 'LGd', 'MH', 'PT', 'PVT', 'CM', 'CL', 'PIL', 'IMD', 'SMT', 'MD', 'RT', 'AV', 'LD', 'LP', 'POL', 'PO', 'IGL', 'LGv', 'TH', 'PM', 'PH', 'VMH', 'MPN', 'TM', 'SUM', 'MM', 'TU', 'LHA', 'RCH', 'PVi', 'DMH', 'ADP', 'MEPO', 'SBPV', 'PV', 'PS', 'HY']: return 'IB'
    if region_parent in ['SNc', 'DR', 'IPDL', 'IPL', 'PPN', 'PBG', 'IC', 'SC', 'SAG', 'INC', 'Su', 'ND', 'PAG', 'VTN', 'VTA', 'CUN', 'PN', 'MT', 'SNr', 'MRN', 'NOT', 'RPF', 'APN', 'PPT', 'MB']: return 'MB'
    return 'Exclude'

def is_visual_area(abbrev, parent):
    abbrev, parent = str(abbrev), str(parent)
    if abbrev.startswith('VIS') and not abbrev.startswith('VISC'): return True
    if parent.startswith('VIS') and not parent.startswith('VISC'): return True
    if abbrev.startswith('LGd') or abbrev.startswith('LGv') or abbrev == 'IGL': return True
    if abbrev == 'SC' or abbrev.startswith(('SCm', 'SCs', 'SCig', 'SCop', 'SCsg', 'SCzo', 'SCdw', 'SCiw', 'SCdg')): return True
    return False

def format_pval(p):
    if p < 0.001:
        return "< 0.001"
    else:
        return f"= {p:.3f}"

scale_factor = 4
w_in = ((58.66 * 1.5) / 25.4) * scale_factor  
h_in = ((56.66 * 1.5) / 25.4) * scale_factor  

# ==========================================
# 3. DATA LOADING AND MERGING HELPER
# ==========================================
def load_and_merge_data(scram_file, z_file):
    # Load Scrambled file (X-axis data)
    df_scram = pd.read_excel(scram_file, sheet_name='All_Subregions_Table', header=None)
    df_scram = df_scram.iloc[2:][[0, 1]].copy() # Rows start at index 2, cols A and B
    df_scram.columns = ['Region', 'X_Val']
    
    # Load Cohen's d file (Y-axis data)
    df_z = pd.read_excel(z_file, sheet_name='All_Subregions_Table', header=None)
    df_z = df_z.iloc[2:][[0, 1]].copy()
    df_z.columns = ['Region', 'Y_Val']
    
    # Merge the dataframes on Region
    df_merged = pd.merge(df_scram, df_z, on='Region', how='inner')
    
    # Force numeric conversion and drop NAs
    df_merged['X_Val'] = pd.to_numeric(df_merged['X_Val'], errors='coerce')
    df_merged['Y_Val'] = pd.to_numeric(df_merged['Y_Val'], errors='coerce')
    df_merged = df_merged.dropna(subset=['Region', 'X_Val', 'Y_Val'])
    
    # Clean region strings and harmonize PTL
    df_merged['Region'] = df_merged['Region'].astype(str).str.strip()
    df_merged['Region'] = df_merged['Region'].replace('PTL', 'PTLp')
    
    return df_merged

# ==========================================
# 4. PLOT GENERATION
# ==========================================
datasets = [
    {
        "scram_file": ai34_scram_file,
        "z_file": ai34_z_file,
        "title": "Ai34 Presynaptic: Scramble vs. Mean", 
        "x_label": "Ai34 Scrambled Log2SD Ratio", 
        "y_label": "Ai34 Average Cohen's d"
    },
    {
        "scram_file": ai14_scram_file,
        "z_file": ai14_z_file,
        "title": "Ai14 Cellular: Scramble vs. Mean", 
        "x_label": "Ai14 Scrambled Log2SD Ratio", 
        "y_label": "Ai14 Average Cohen's d"
    }
]

for ds in datasets:
    print(f"Processing {ds['title']}...")
    try:
        # Load and merge the specific datasets dynamically
        df = load_and_merge_data(ds['scram_file'], ds['z_file'])
        
        # Apply anatomical mapping
        df['Parent'] = df['Region'].map(abbrev_to_parent).fillna(df['Region'])
        df['Base_Group'] = df['Parent'].apply(get_base_group)
        df['is_VS'] = df.apply(lambda row: is_visual_area(row['Region'], row['Parent']), axis=1)
        df.loc[df['is_VS'] == True, 'Base_Group'] = 'VS'

        df = df[~df['Region'].str.startswith(('MOB', 'AOB'))]
        df = df[df['Base_Group'] != 'Exclude'].copy()
        df['Plot_Color'] = df['Base_Group'].map(allen_colors)
        
        # Generate Plot
        fig, ax = plt.subplots(figsize=(w_in, h_in), dpi=600) 
        
        x_min, x_max = df['X_Val'].min(), df['X_Val'].max()
        y_min, y_max = df['Y_Val'].min(), df['Y_Val'].max()
        
        x_pad = (x_max - x_min) * 0.15
        y_pad = (y_max - y_min) * 0.15
        if x_pad == 0: x_pad = 0.5
        if y_pad == 0: y_pad = 0.5
            
        ax.set_xlim(x_min - x_pad, x_max + x_pad)
        ax.set_ylim(y_min - y_pad, y_max + y_pad)
        
        dot_size = 90
        dot_alpha = 0.75
        ax.scatter(df['X_Val'], df['Y_Val'], color=df['Plot_Color'], s=dot_size, alpha=dot_alpha, edgecolors='white', linewidth=0.5)
        
        if len(df) > 2:
            rho, p_val = spearmanr(df['X_Val'], df['Y_Val'])
            slope, intercept = np.polyfit(df['X_Val'], df['Y_Val'], 1)
            x_vals = np.array(ax.get_xlim()) 
            y_vals = intercept + slope * x_vals
            ax.plot(x_vals, y_vals, color='black', linewidth=3.5, linestyle='-', zorder=1)
            stat_text = f"$\\rho$ = {rho:.3f}\n$p$ {format_pval(p_val)}"
        else:
            stat_text = "N/A"

        if ax.get_xlim()[0] < 0 < ax.get_xlim()[1]:
            ax.axvline(0, color='black', linestyle=':', alpha=0.5, zorder=0, lw=1.5)
        if ax.get_ylim()[0] < 0 < ax.get_ylim()[1]:
            ax.axhline(0, color='black', linestyle=':', alpha=0.5, zorder=0, lw=1.5)
        
        ax.set_xlabel(ds['x_label'], fontsize=18, fontweight='bold', labelpad=8)
        ax.set_ylabel(ds['y_label'], fontsize=18, fontweight='bold', labelpad=8)
        ax.set_title(ds['title'], fontsize=22, fontweight='bold', pad=15)
        ax.tick_params(axis='both', which='major', labelsize=14)
        
        props = dict(boxstyle='round', facecolor='white', alpha=0.9, edgecolor='gray', lw=1.0)
        ax.text(0.03, 0.97, stat_text, transform=ax.transAxes, fontsize=16, verticalalignment='top', bbox=props, zorder=5)
        
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

        plt.tight_layout()
        clean_title = ds['title'].replace(":", "").replace(" ", "_").replace(".", "")
        filename = f"{output_dir}Correlation_Plot_{clean_title}.png"
        plt.savefig(filename, dpi=600, bbox_inches='tight')
        plt.close()
        
    except Exception as e:
        print(f"  -> Error processing {ds['title']}: {e}")

print(f"\nFinished! Check {output_dir} for your output plots.")