# Quad plot figure generator from precalculated Master Excel tables, Ai14
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as PathEffects
import re
import os
import warnings

warnings.filterwarnings('ignore')

# ==========================================
# 1. FILE PATHS & SETUP
# ==========================================
base_dir = r"..\data"
output_dir = r"..\output\\" 

# Input files generated by your previous scripts
mean_file = os.path.join(base_dir, "Ai14_Master_Tables_Formatted.xlsx")
var_file = os.path.join(base_dir, "Ai14_Levene_Master_Tables.xlsx")
ccf_csv = os.path.join(base_dir, "CCFv3-2020_info_oliver_voxel_info.csv")

reporter = "Ai14" 

# ==========================================
# 2. LOAD DATA FROM EXCEL
# ==========================================
print("Extracting metrics from Master Excel files...")
# Load the 'All_Subregions_Table' sheet, skipping the 2-row header
df_mean = pd.read_excel(mean_file, sheet_name='All_Subregions_Table', header=None, skiprows=2)
df_var = pd.read_excel(var_file, sheet_name='All_Subregions_Table', header=None, skiprows=2)

# Isolate Region (Col 0) and the calculated metric (Col 1)
df_mean = df_mean[[0, 1]].rename(columns={0: 'Region', 1: 'Avg_Cohens_d'})
df_var = df_var[[0, 1]].rename(columns={0: 'Region', 1: 'Avg_Log2_Std_Ratio'})

# Merge the two metrics into a single DataFrame for plotting
df = pd.merge(df_mean, df_var, on='Region', how='inner')

# Clean regions
df['Region'] = df['Region'].astype(str).str.strip()
df['Region'] = df['Region'].replace('PTL', 'PTLp')

# Filter out empty rows
df = df.dropna(subset=['Avg_Cohens_d', 'Avg_Log2_Std_Ratio'])

# ==========================================
# 3. ALLEN ATLAS MAPPING LOGIC 
# ==========================================
print("Mapping anatomical groups...")
ccf_df = pd.read_csv(ccf_csv)
abbrev_to_parent = dict(zip(ccf_df['abbreviation'], ccf_df['region']))
abbrev_to_parent['PTLp'] = 'PTLp'

allen_colors = {
    'Isocortex': '#66C2A5', 'HPF': '#7ED04B', 'CTXsp': '#8DD3D7', 
    'CNU': '#98D6F9', 'IB': '#FF7080', 'MB': '#FF64FF', 'VS': '#B39DDB'         
}

def get_base_group(region_parent):
    if region_parent in ['PL', 'ILA', 'AI', 'PERI', 'ECT', 'ORB', 'VISC', 'VIS', 'TEa', 'MO', 'SS', 'ACA', 'RSP', 'AUD', 'PTLp', 'FRP', 'GU', 'ISO']: return 'Isocortex'
    if region_parent in ['ENT', 'PAR', 'HATA', 'SUB', 'ProS', 'PRE', 'POST', 'DG', 'CA3', 'CA2', 'CA1', 'IG', 'HPF', 'RHP', 'HIP', 'FC']: return 'HPF'
    if region_parent in ['EP', 'PA', 'CLA', 'BMA', 'BLA', 'LA', 'CTXsp']: return 'CTXsp'
    if region_parent in ['SI', 'MS', 'TRS', 'GP', 'BST', 'PAL', 'FS', 'OT', 'ACB', 'CP', 'MEA', 'AAA', 'IA', 'SH', 'SF', 'LS', 'STR']: return 'CNU'
    if region_parent in ['VPM', 'VPL', 'VM', 'VAL', 'SPA', 'SPF', 'LGd', 'MH', 'PT', 'PVT', 'CM', 'CL', 'PIL', 'IMD', 'SMT', 'MD', 'RT', 'AV', 'LD', 'LP', 'POL', 'PO', 'IGL', 'LGv', 'TH', 'PM', 'PH', 'VMH', 'MPN', 'TM', 'SUM', 'MM', 'TU', 'LHA', 'RCH', 'PVi', 'DMH', 'ADP', 'MEPO', 'SBPV', 'PV', 'PS', 'HY']: return 'IB'
    if region_parent in ['SNc', 'DR', 'IPDL', 'IPL', 'PPN', 'PBG', 'IC', 'SC', 'SAG', 'INC', 'Su', 'ND', 'PAG', 'VTN', 'VTA', 'CUN', 'PN', 'MT', 'SNr', 'MRN', 'NOT', 'RPF', 'APN', 'PPT', 'MB']: return 'MB'
    return 'Exclude'

def is_visual_area(abbrev, parent):
    abbrev, parent = str(abbrev), str(parent)
    if abbrev.startswith('VIS') and not abbrev.startswith('VISC'): return True
    if parent.startswith('VIS') and not parent.startswith('VISC'): return True
    if abbrev.startswith('LGd') or abbrev.startswith('LGv') or abbrev == 'IGL': return True
    if abbrev == 'SC' or abbrev.startswith(('SCm', 'SCs', 'SCig', 'SCop', 'SCsg', 'SCzo', 'SCdw', 'SCiw', 'SCdg')): return True
    return False

df['Parent'] = df['Region'].map(abbrev_to_parent).fillna(df['Region'])
df['Base_Group'] = df['Parent'].apply(get_base_group)
df['is_VS'] = df.apply(lambda row: is_visual_area(row['Region'], row['Parent']), axis=1)

df.loc[df['is_VS'] == True, 'Base_Group'] = 'VS'
df = df[~df['Region'].astype(str).str.startswith(('MOB', 'AOB'))]
df = df[df['Base_Group'] != 'Exclude'].copy()
df['Plot_Color'] = df['Base_Group'].map(allen_colors)

def format_label(region):
    if '-' in region: return region.replace('-', '\n')
    match = re.search(r'(1|2/3|4|5|6a|6b|6)$', region)
    if match:
        layer = match.group(1)
        base = region[:-len(layer)]
        if base: return f"{base}\n{layer}"
    return region 

# ==========================================
# 4. EXACT PROPORTIONAL SIZING (Grid Target)
# ==========================================
scale_factor = 4
w_in = (58.66 / 25.4) * scale_factor  
h_in = (56.66 / 25.4) * scale_factor  

groups_to_plot = ['Isocortex', 'HPF', 'CTXsp', 'CNU', 'IB', 'MB', 'VS', 'Whole Brain']

for target_group in groups_to_plot:
    print(f"Generating high-res proportional plot for {target_group}...")
    
    fig, ax = plt.subplots(figsize=(w_in, h_in), dpi=600) 
    
    x_all = df['Avg_Cohens_d']
    y_all = df['Avg_Log2_Std_Ratio']
    
    if target_group == 'Whole Brain':
        target_mask = pd.Series([True]*len(df), index=df.index)
        group_color = df['Plot_Color'] 
    else:
        target_mask = df['Base_Group'] == target_group
        group_color = allen_colors[target_group]
        
    df_target = df[target_mask]
    
    # ----------------------------------------------------
    # FIXED AXES AND TICKS
    # ----------------------------------------------------
    ax.set_xlim(-2.0, 2.0)
    ax.set_ylim(-2.0, 2.0)
    ax.set_xticks(np.arange(-2.0, 2.5, 0.5))
    ax.set_yticks(np.arange(-2.0, 2.5, 0.5))
    
    if target_group != 'Whole Brain':
        ax.scatter(x_all[~target_mask], y_all[~target_mask], color='#D3D3D3', s=50, alpha=0.4, edgecolors='none')
    
    dot_size = 60 if target_group == 'Whole Brain' else 180
    dot_alpha = 0.7 if target_group == 'Whole Brain' else 0.55
    ax.scatter(df_target['Avg_Cohens_d'], df_target['Avg_Log2_Std_Ratio'], color=group_color, s=dot_size, alpha=dot_alpha, edgecolors='white', linewidth=0.5)

    if target_group != 'Whole Brain':
        for _, row in df_target.iterrows():
            # Only add labels if the point is within the plotting boundaries to prevent clipping issues
            if -2.0 <= row['Avg_Cohens_d'] <= 2.0 and -2.0 <= row['Avg_Log2_Std_Ratio'] <= 2.0:
                stacked_name = format_label(row['Region'])
                txt = ax.text(
                    row['Avg_Cohens_d'], row['Avg_Log2_Std_Ratio'], stacked_name, 
                    fontsize=8, fontweight='normal', color='black', 
                    ha='center', va='center', 
                    transform=ax.transData, zorder=10 
                )
                txt.set_path_effects([PathEffects.withStroke(linewidth=1.5, foreground='white', alpha=0.8)])

    ax.axvline(0, color='black', linestyle=':', alpha=0.5, zorder=0, lw=1.5)
    ax.axhline(0, color='black', linestyle=':', alpha=0.5, zorder=0, lw=1.5)
    
    ax.set_xlabel("Cohen's d", fontsize=16, fontweight='bold', labelpad=6)
    ax.set_ylabel("Log2 Std Ratio", fontsize=16, fontweight='bold', labelpad=6)
    ax.set_title(target_group, fontsize=18, fontweight='bold', pad=12)
    ax.tick_params(axis='both', which='major', labelsize=12)
    
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    filename = f"{output_dir}{reporter}_QuadPlot_{target_group.replace(' ', '_')}.png"
    plt.savefig(filename, dpi=600, bbox_inches='tight')
    plt.close()

print(f"Success! All 8 fixed-scale plots saved to {output_dir}")